---
- name: Getting started ansible
  hosts: all
  become: true
  pre_tasks:
    - name: install update (CentOS)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"
    - name: install update (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
- name: Another one
  hosts: web_servers
  become: true
  tasks:
    - name: Install the apache2 package and php package and update cache for Ubuntu
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
    - name: Install the apache2 package and phh package and update cache for CentOS
      tags: apache,centos,httpd
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"
- name: onther one with db servers
  hosts: db_servers
  become: true
  tasks:
   - name: Install Maria package (CentOS)
     tags: centos,db,mariadb
     dnf:
       name: mariadb
       state: latest
     when: ansible_distribution == "CentOS"
   - name: Install Maria package (Ubuntu)
     tags: db,mariadb,ubuntu
     apt:
       name: mariadb-server
       state: latest
     when: ansible_distribution == "Ubuntu"
- name: play for the fileservers
  hosts: file_servers
  become: true
  tasks:
   - name: Install Samba Package
     tags: samba
     package:
       name: samba
       state: latest
